### ISSUE TITLE
Consistent api names

### ISSUE THREAD

**Issue by Minhir** [effector/keyval#9]
Now we have few api names like `setField`, `removeByField`, `mapItem`, `removeItem`, `addItem`, `addItemTree`

Looks like all of these methods about item. So we can remove the word `Item` from every method. Or we can keep it everywhere, including `setItemField`, `removeItemByField`

**Comment by zerobias** [comment]
Yes, names need consistency. Curiously, -Item suffix is a lie as removeItem can remove many items at once, but we probably can’t drop it entirely as there are methods which works on entire kv like setAll or removeByField
